### ISSUE TITLE
Can not find tsfile-format.properties

### ISSUE THREAD

**Issue by qiaojialin** [thulab/tsfile#71]
When using TsFile, it can not read the properties file
`java.io.FileNotFoundException: src/test/resources/tsfile-format.properties (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at cn.edu.tsinghua.tsfile.common.conf.TSFileDescriptor.loadProps(TSFileDescriptor.java:45)`

It should uses the getResources method

**Comment by MyXOF** [comment]
Can you reproduce the problem?Screenshot to me

**Comment by MyXOF** [comment]
solve in https://github.com/thulab/tsfile/pull/74
