### ISSUE TITLE
Write negative array to outputstream

### ISSUE THREAD

**Issue by liukun4515** [thulab/tsfile#77]
Exception:
```
09:26:26.295 [main] WARN  c.e.t.t.t.write.InternalRecordWriter - too large actual row group size!:actual:2208,threshold:2000
Exception in thread "main" java.lang.NegativeArraySizeException
	at cn.edu.tsinghua.tsfile.timeseries.write.io.TSFileIOWriter.fillInRowGroup(TSFileIOWriter.java:198)
	at cn.edu.tsinghua.tsfile.timeseries.write.InternalRecordWriter.fillInRowGroupSize(InternalRecordWriter.java:166)
	at cn.edu.tsinghua.tsfile.timeseries.write.InternalRecordWriter.flushRowGroup(InternalRecordWriter.java:151)
	at cn.edu.tsinghua.tsfile.timeseries.write.InternalRecordWriter.checkMemorySize(InternalRecordWriter.java:123)
	at cn.edu.tsinghua.tsfile.timeseries.write.InternalRecordWriter.write(InternalRecordWriter.java:74)
	at cn.edu.tsinghua.tsfile.timeseries.basis.TsFile.writeLine(TsFile.java:110)
	at cn.edu.thu.tsfile.hadoop.TsFileTestHelper.writeTsFile(TsFileTestHelper.java:48)
	at cn.edu.thu.tsfile.hadoop.TsFileTestHelper.main(TsFileTestHelper.java:103)
```
Code:
```
    public void fillInRowGroup(long diff) throws IOException {
        if (diff <= Integer.MAX_VALUE)
            out.write(new byte[(int) diff]);
        else
            throw new IOException("write too much blank byte array!array size:" + diff);
    }
```

**Comment by jixuan1989** [comment]
Has anyone solved the bug? @kr11 @liukun4515
